version: '3'
services:
  myservice:
    container_name: webserver_container

    build: .
    ports:
      - "80:8000"
    volumes:
      - "${PWD}/config/config.ini:/app/config.ini"
      - "${PWD}/templates:/app/templates"
      - "${PWD}/dist"

