version: '3'
services:
  myservice:
    container_name: webserver_container
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./config/config.ini:/app/config.ini
      - ./templates:/app/templates
      - ./dist:/app/dist
      - ./data:/app/data

